### PR TITLE
Add Operations use cases

### PR DESCRIPTION
**Pull request by ChristianKoehler**
The dockerfile slipped in. :(

### CODE REVIEW

**Comment by dataduke** [comment]
new pr please or merge manually in master.  you have been added to the repo admin list. ;-)

**Comment by dataduke** [comment]
hast jetzt rechte

**Comment by dataduke** [comment]
btw does this Dockerfile work? would be nice to include too!

**Comment by ChristianKoehler** [comment]
Sure it does!

```
docker build -t reveal-md .
docker run -p 8080:8080 -v /$PWD/talk:/data reveal-md
```

**Pull request merged**
